input_path=/{ABSOLUTE_PATH}/artifacts_input       # Location of artifacts to be analyzed. Do not specify last /
output_path=/{ABSOLUTE_PATH}/scans_output         # Location where analysis results will be stored. Do not specify last /
os="windows"
HASH_ALGO="sha256"
## ELK INSTANCE
EXPORT2ELK=true
## TIMESKETCH INSTANCE
EXPORT2TIMESKETCH=true
timesketch_sketch_id={SKETCH_ID}                # Need to be created on Timesketch Instance webpage manually
timesketch_user="{ANSIBLE_USER}"
timesketch_password="{PASSWORD}"                # Generated by keepassXC during ansible installation
timesketch_upload_path="/home/{ANSIBLE_USER}/Documents/Tools/DFIR/timesketch/timesketch/upload"
