- name: Hayabusa - Build image
  community.docker.docker_image:
    name: hayabusa
    build:
      path: ../
      dockerfile: dockers/hayabusa_dockerfile
    source: build
    state: present

- name: Hayabusa - Build image container
  community.docker.docker_container:
    name: hayabusa
    image: hayabusa
    recreate: true
    restart: no
    restart_policy: "no"
    state: "stopped"
