input {
  file {
        path => "/opt/data/report-chainsaw.jsonl"
        mode => "read"
        exit_after_read => true
        file_completed_action => "log"
        file_completed_log_path => "/usr/share/logstash/logstash_ingest_completed.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        type => "chainsaw"
  }
}

filter {
    if ([type] == "chainsaw") {
        json {
            source => "message"
            add_tag => ["chainsaw"]
        }
    }
}

output {
  if ([type] == "chainsaw") {
    elasticsearch {
      hosts => ["elasticsearch:9200"] 
      index => "chainsaw"
    }
  }
}
