version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: oreo_redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oreo_network

volumes:
  redis_data:

networks:
  oreo_network:
    driver: bridge
