input {
  file {
        path => "/opt/data/report-hayabusa.jsonl"
        mode => "read"
        exit_after_read => true
        file_completed_action => "log"
        file_completed_log_path => "/usr/share/logstash/logstash_ingest_completed.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        type => "hayabusa"
  }
}

filter {
    if ([type] == "hayabusa") {
        json {
            source => "message"
            add_tag => ["hayabusa"]
        }
        mutate {
            remove_field =>["RuleModifiedDate"]
            convert => {
              "Details.PID" => "string"
            }
        }
        if ([Details][PID] == "n/a"){
            mutate {
              update => {
                "Details.PID" => "-1"
              }
            }
        }
    }
}


output {
  if ([type] == "hayabusa") {
    elasticsearch {
      hosts => ["elasticsearch:9200"] 
      index => "hayabusa"
    }
  }
}
