input {
  file {
        path => "/opt/data/exportForTimesketch_*.json"
        mode => "read"
        exit_after_read => true
        file_completed_action => "log"
        file_completed_log_path => "/usr/share/logstash/logstash_ingest_completed.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        type => "zircolite"
  }
}

filter {
    if ([type] == "zircolite") {
        json {
            source => "message"
            add_tag => ["zircolite"]
        }
    }

    mutate {
      add_field => {
        "[event][kind]" => "suspicious_event"
      }
    }

}

output {
  if ([type] == "zircolite") {
    elasticsearch {
      hosts => ["elasticsearch:9200"] 
      index => "zircolite_suspicious_event"
    }
  }
}
